import { IsString, Length } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class FixKeyMismatchDto {
  @ApiProperty({
    description: 'Unique device identifier',
    example: 'android_honorrmo-n21_goovi.almusawi.vpn',
  })
  @IsString()
  @Length(1, 100)
  deviceId: string;

  @ApiProperty({
    description: 'New WireGuard public key generated by client',
    example: 'CZiCVeZpKH97PNrY/1rodYAPeLDF3AaPrxFo+gOnLx8=',
  })
  @IsString()
  @Length(44, 44, { message: 'WireGuard public key must be exactly 44 characters' })
  newPublicKey: string;
}

export class UpdatePublicKeyDto {
  @ApiProperty({
    description: 'New WireGuard public key generated by client',
    example: 'CZiCVeZpKH97PNrY/1rodYAPeLDF3AaPrxFo+gOnLx8=',
  })
  @IsString()
  @Length(44, 44, { message: 'WireGuard public key must be exactly 44 characters' })
  publicKey: string;
}
